### ISSUE TITLE
hardcoded bucket "tatt_transcript_goog" for Google

### ISSUE THREAD

**Issue by ad-m** [zevaverbach/tatt#69]
I have tried to use this tool. Unfortunately, I miss access to the hardcoded bucket `tatt_transcript_goog` on Google.

```
$ transcribe this /tmp/skw\ cz1.mp3 google
Traceback (most recent call last):
  File "/tmp/tmp.RSx3Aji6YS/bin/transcribe", line 5, in <module>
    from tatt.transcribe import cli
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/tatt/transcribe.py", line 8, in <module>
    from tatt import config, exceptions, helpers, vendors
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/tatt/helpers.py", line 8, in <module>
    from tatt import config, exceptions, vendors
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/tatt/vendors/__init__.py", line 1, in <module>
    from tatt.vendors import amazon, google
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/tatt/vendors/google.py", line 29, in <module>
    class Transcriber(TranscriberBaseClass):
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/tatt/vendors/google.py", line 168, in Transcriber
    transcript_bucket = storage_client.get_bucket(BUCKET_NAME_TRANSCRIPT)
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/storage/client.py", line 780, in get_bucket
    bucket.reload(
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/storage/bucket.py", line 1029, in reload
    super(Bucket, self).reload(
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/storage/_helpers.py", line 232, in reload
    api_response = client._get_resource(
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/storage/client.py", line 364, in _get_resource
    return self._connection.api_request(
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/tmp/tmp.RSx3Aji6YS/lib/python3.9/site-packages/google/cloud/_http/__init__.py", line 480, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/tatt_transcript_goog?projection=noAcl&prettyPrint=false: tatt-transcribe@lf-course.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

**Comment by zevaverbach** [comment]
hey @ad-m, sorry not to have seen this comment 'til now! I will have a look soon hopefully.
